anchor_version = "0.19.0"

[workspace]
members = [
    "programs/chicks-staking-flexible"
]

[registry]
url = "https://anchor.projectserum.com"

[programs.localnet]
chicks_staking_flexible = "XASp8U7ZSJ9sJfUaMKk5dxuw3Hf4xkLPBcoHZ4seoC1"

#[provider]
#cluster = "localnet"
#wallet = "/home/bmstart/work/solana/keys/alice.json"

#[provider]
#cluster = "mainnet"
#wallet = "/home/bmstart/work/solana/keys/alice.json"

# for devnet
[provider]
cluster = "devnet"
wallet = "/home/bmstart/work/solana/keys/alice.json"

[scripts]
test = "mocha -t 1000000 tests/"
#[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
